repos:
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    - id: black
      language_version: python3.12
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]