name: Validate
on:
  push:
    branches: [ main]
    paths:
      - '.github/workflows/validate.yaml'
      - 'sources/**'
      - 'source.schema.json'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/validate.yaml'
      - 'sources/**'
      - 'source.schema.json'
env:
  AWS_ENDPOINT_URL: "https://nrs.objectstore.gov.bc.ca"
  AWS_S3_ENDPOINT: "nrs.objectstore.gov.bc.ca"
  AWS_VIRTUAL_HOSTING: "FALSE"
  AWS_EC2_METADATA_DISABLED: "true"
  CPL_VSISTDIN_BUFFER_LIMIT: -1
  BUCKET: ${{ secrets.BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  get-matrix:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Install tool
        run: |
          python -m pip install .
      - id: set-matrix
        run: |
          DATA=$(changedetector list-configs | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$DATA" >> $GITHUB_OUTPUT
  validate:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/fit_changedetector:main
    environment: production
    needs: get-matrix
    strategy:
      fail-fast: false
      matrix:
        arg: ${{fromJson(needs.get-matrix.outputs.matrix)}}
    env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4
      - name: Install tool
        run: |
          python -m pip install .
      - name: Validate all sources
        run: |
          changedetector process -Vv sources/${{ matrix.arg }}.json